### ISSUE TITLE
[Feature] Improve async resource loading by adding async/await support.

### ISSUE THREAD

**Issue by DuckerMan** [mrDIMAS/rg3d#23]
Hi there! I think it'd be better to make [https://docs.rs/rg3d/0.11.0/rg3d/engine/resource_manager/struct.ResourceManager.html#method.request_texture_async](this method) supports rust `async/await`.

**Comment by mrDIMAS** [comment]
Hello, I need to learn async\await in Rust before doing that 🙂 
Resource manager still lacks proper async resource loading support, I'm currently busy with editor for engine and UI library, so have no idea when I'll have time to improve this.

**Comment by mrDIMAS** [comment]
I'm closing this, because recently I added async/.await texture loading. See #40 for more details.
