### ISSUE TITLE
Change the absolute path to a published crates for examples.

### ISSUE THREAD

**Issue by alekspickle** [mrDIMAS/rg3d#35]
As I understand it is more convenient if you are developing this alone, but this will improve time to dive into you engine. 
Love it by the way!

I can send a PR if you don't have any objection.

**Comment by mrDIMAS** [comment]
Hello! I understand that it is a bit unusual to clone/pull 5 repos to compile an example, but published crates usually way too outdated and examples most likely won't compile, so I'd leave it as it is.

**Comment by alekspickle** [comment]
Understandable. If thats the case, consider merging #36!
Keep up the good work! I personally would like to see this project grow into something great!

**Comment by mrDIMAS** [comment]
I'm closing this because I've moved dependencies in the workspace of the project so there is no need to download them separately in order to make things compile.
