### ISSUE TITLE
Texture Filtering Setting?

### ISSUE THREAD

**Issue by itmuckel** [mrDIMAS/rg3d#39]
This might be an exotic request, but I started doing low poly modeling with pixely textures. In Blender I can set the interpolation mode to closest (= GL_NEAREST). rg3d seems to set it to LINEAR (or Blender doesn't export it into FBX correctly?).

Is this something that rg3d reads from file?

**Comment by mrDIMAS** [comment]
It is very simple to fix, I'll add filtering options for Texture as soon as possible, will keep you posted.

**Comment by mrDIMAS** [comment]
So I added [TextureMinificationFilter](https://github.com/mrDIMAS/rg3d/blob/master/src/resource/texture.rs#L119) and [TextureMagnificationFilter](https://github.com/mrDIMAS/rg3d/blob/master/src/resource/texture.rs#L81), filtering could be set after loading a texture by calling [set_minification_filter](https://github.com/mrDIMAS/rg3d/blob/master/src/resource/texture.rs#L317) and [set_magnification_filter](https://github.com/mrDIMAS/rg3d/blob/master/src/resource/texture.rs#L327). Also I added ability to change anisotropy level in anisotropic filtering, previously it was automatically set to maximum anisotropy level of your hardware.

**Comment by itmuckel** [comment]
Thanks! It works!
Although it feels a bit hacky and I'm not sure if I'm doing it correctly:
```rust
    let model_resource = resource_manager
        .request_model("assets/items.fbx")
        .unwrap();

    resource_manager.find_texture("assets/ImphenziaPalette01.png").unwrap().lock().unwrap().set_minification_filter(TextureMinificationFilter::Nearest);
    resource_manager.find_texture("assets/ImphenziaPalette01.png").unwrap().lock().unwrap().set_magnification_filter(TextureMagnificationFilter::Nearest);
```

Here the texture lies next to the fbx file and I can do this pretty easily. So when I have more than 1 model I can loop over all images in the asset directory and set it like this? Can I give the ResourceManager a default setting somehow? 🤔

**Comment by mrDIMAS** [comment]
Right now there is no import options, I'll try to add them asap.

**Comment by mrDIMAS** [comment]
I added [TextureImportOptions](https://github.com/mrDIMAS/rg3d/blob/master/src/engine/resource_manager.rs#L101), you can set minification and magnification filters as well as default anisotropy level.

**Comment by itmuckel** [comment]
Wow, thanks for the quick fix! 🙏
