### ISSUE TITLE
Low fps for little geometry?

### ISSUE THREAD

**Issue by itmuckel** [mrDIMAS/rg3d#41]
Context: I'm playing around with level generation and wanted to generate some rooms.

So I generated a map and instanced the floor tiles like this:
```rust
        for x in 0..level.map.len() {
            for y in 0..level.map[0].len() {
                if level.map[x][y] == 0 {
                    continue;
                }

                let floor_handle = floor_resource
                    .lock()
                    .unwrap()
                    .instantiate_geometry(&mut scene);

                scene.graph[floor_handle]
                    .local_transform_mut()
                    .set_scale(Vec3::new(0.2, 0.2, 0.2));

                scene.graph[floor_handle]
                    .local_transform_mut()
                    .offset(Vec3::new(20.0 * x as f32, 0.0, 20.0 * y as f32));
            }
        }
```
A floor tile has 8 vertices and a 16x16px texture. I'm rendering 2032 tiles in this example:

![grafik](https://user-images.githubusercontent.com/18561536/96943431-6aaac500-14d8-11eb-8c2d-5b867167e738.png)

I shrunk the window down to less then a quarter of my 4k screen, so the resolution shouldn't be a problem.
Also I set the quality settings to low (no ssao, also no lights in the scene except ambient "light").

Any idea why it performs so poorly? My PC runs Witcher 3 at max details in 2k resolution at nearly 60fps, so I don't think the polygon count is a problem here. 😅

**Comment by mrDIMAS** [comment]
Was it in Release? Make sure you `cargo run --release`, in Debug it will be slow. 
Also at how much FPS do you have in 3rd_person example (`cargo run --example 3rd_person --release`)?

**Comment by mrDIMAS** [comment]
Also instead of this 
```
scene.graph[floor_handle]
	.local_transform_mut()
	.set_scale(Vec3::new(0.2, 0.2, 0.2));

scene.graph[floor_handle]
	.local_transform_mut()
	.offset(Vec3::new(20.0 * x as f32, 0.0, 20.0 * y as f32));
```

You could chain calls like this:

```rust
scene.graph[floor_handle]
	.local_transform_mut()
	.set_scale(Vec3::new(0.2, 0.2, 0.2))
	.offset(Vec3::new(20.0 * x as f32, 0.0, 20.0 * y as f32));
```

**Comment by itmuckel** [comment]
Ah, yes, in release mode it runs at 60fps at 4k.
(The 3rd_person example runs only at 20fps with the highest quality settings, but that might be okay, I don't know what calculations go on in the background.)

Why is the runtime performance so different? That's also a bit problematic for development, because the edit-compile-test cycle is quite fast in gamedev and compile times should be as fast as possible. Can you explain why it has to be slow in debug mode?

Thanks for the chaining tip! :)

**Comment by mrDIMAS** [comment]
Debug has optimizations turned off. You can set optimization level for dependencies separately by adding this into your Cargo.toml

```toml
[profile.dev.package."*"]
opt-level = 2
```

This will enable optimization for dependencies, but your project will remain unoptimized which will improve build times a bit.

**Comment by itmuckel** [comment]
Wow, extremely useful tip! Thank you! What's the worst thing that can happen now with opt-level 3? Unreadable stack trace when a library panics somewhere? 🤔

**Comment by mrDIMAS** [comment]
Yeah, stack trace might be useless with opt-level=3, however even with level 2 it is barely useful.
