### ISSUE TITLE
Rust-gpu instead of GLSL?

### ISSUE THREAD

**Issue by NangiDev** [mrDIMAS/rg3d#60]
I saw that there was some GLSL involed and just wanted to tell you that Embark studios is working on a GLSL Rust replacement.

https://github.com/EmbarkStudios/rust-gpu

**Comment by mrDIMAS** [comment]
Hello! I know about this crate, but it is not suitable for rg3d because rg3d aims for low-end and relatively old hardware too as well as modern GPUs. Also rust-gpu seems to be immature and I don't want to fight with random bugs from it, I have OpenGL already :smile:

**Comment by NangiDev** [comment]
I understand :D I just thought I would share just in case.
Still an interesting project you got going. I will try to look more into it soon.

I would say this issue is resolved now so I will close it :P
