### ISSUE TITLE
Sound: Play one-off sound, then stop audio thread again?

### ISSUE THREAD

**Issue by BafDyce** [mrDIMAS/rg3d#66]
I would like to add some sound an application. However, I only need to play a short sound (a few seconds) every few minutes. When using `rg3d-sound`, the `Context` spawns a mixer thread in the background which consumes 100% cpu (of one core). Unfortunately, I cannot find a way to stop this thread again (not even if I execute `std::mem::drop(context)` after playing the sound).

Is there some way to create a `Context` in such a way that it automatically stops itself again after playing the sound, so that my application doesnt need that high CPU resources all the time?

**Comment by mrDIMAS** [comment]
Hello! It actually sounds like a bug in a backend. Which OS do you use? 

I just checked how it works on Windows and single core load was around 2-5%.

**Comment by BafDyce** [comment]
Hi! Thanks for the quick response, given that its holiday season :)

I'm on Linux, so using the alsa backend.

**Comment by mrDIMAS** [comment]
Should be fixed now. Changes are in https://github.com/mrDIMAS/rg3d/commit/34591e9553ace577b8f2616ea5062a8ee947764a . Could you please confirm if CPU usage is ok now?

**Comment by mrDIMAS** [comment]
I checked on virtual machine and it was something around 0.6-1.0%, previously it was ~98%.

**Comment by BafDyce** [comment]
Thanks for the quick work! Regarding the fix: Well, yes but no?

Yes, the CPU load decreased significantly. However, it seems like it doesnt play any sound anymore? Maybe I'm just missing something because the API has slightly changed?

My code before:

```rust
// rg3d-sound = "0.18.0"
pub struct MyStruct {
    context: Arc<Mutex<Context>>,
    active_handles: Vec<(Instant, Handle<SoundSource>)>,
}

impl MyStruct {
pub fn play(&mut self, sound: MySound) {
    let data_source = sound.data_source();
    match SoundBuffer::new_generic(data_source) {
        Ok(sound_buffer) => {
            let source_builder = GenericSourceBuilder::new(sound_buffer)
                .with_status(Status::Playing)
                .with_play_once(true);
            match source_builder.build_source() {
                Ok(source) => {
                    match self.context.lock() {
                        Ok(mut context_lock) => {
                            let source_handle: Handle<SoundSource> = context_lock.add_source(source);

                            let expiry = Instant::now() + sound.duration();
                            self.active_handles.push((expiry, source_handle));
                        }
                        Err(err) => {
                            error!("Failed to play sound: {}", err);
                        }
                    }

                }
                Err(err) => {
                    error!("Failed to build source for {:?}: {}", sound, err);
                }
            }
        }
        Err(_) => {
            error!("Could not create SoundBuffer");
        }
    }
}
}
```

This correctly plays sounds but uses 100% CPU as described above.

My code afterwards:

```rust
// rg3d-sound = { git = "https://github.com/mrDIMAS/rg3d", rev = "34591e9" }
pub struct MyStruct {
    context: Context,
    active_handles: Vec<(Instant, Handle<SoundSource>)>,
}

impl MyStruct {
    pub fn play(&mut self, sound: MySound) {
        let data_source = sound.data_source();
        match SoundBuffer::new_generic(data_source) {
            Ok(sound_buffer) => {
                let source_builder = GenericSourceBuilder::new(sound_buffer)
                    .with_status(Status::Playing)
                    .with_play_once(true);
                match source_builder.build_source() {
                    Ok(source) => {
                        let mut state = self.context.state();
                        let source_handle = state.add_source(source);

                        let expiry = Instant::now() + sound.duration();
                        self.active_handles.push((expiry, source_handle));
                    }
                    Err(err) => {
                        error!("Failed to build source for {:?}: {}", sound, err);
                    }
                }
            }
            Err(_) => {
                error!("Could not create SoundBuffer");
            }
        }
    }
}
```

This consumes very few CPU but plays no sounds. Do I need to change something else as well (some other changes since 0.18.0)?

**Comment by BafDyce** [comment]
Note: I don't know if its a side effect or if it worked before already but (at least on my system) sounds also play flawlessly now in debug mode.

**Comment by mrDIMAS** [comment]
Cool. Yeah, I changed design a bit to support multiple contexts. I'm closing the issue then, it is good that you spotted this issue, thanks! I'll try to publish 0.19.0 on crates.io as soon as possible.
