### ISSUE TITLE
How does it compare to CryEngine

### ISSUE THREAD

**Issue by zhuxiujia** [mrDIMAS/rg3d#77]
How does it compare to CryEngine？

**Comment by mrDIMAS** [comment]
I can't compare rg3d with CryEngine because I didn't try it. One thing I can say for sure: with rg3d you will not have weird crashes, at max only panics.

**Comment by zhuxiujia** [comment]
> I can't compare rg3d with CryEngine because I didn't try it. One thing I can say for sure: with rg3d you will not have weird crashes, at max only panics.

CryEngine is pretty much the best graphics quality engine in my opinion
